import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
// Playwright runs this file's tests across several worker *processes* — an
// in-memory array only ever sees the subset one worker happened to run, so
// each test writes its own per-route result to disk here instead, and
// globalTeardown (see playwright.config.ts) aggregates every file in this
// directory into docs/accessibility-test-results.md exactly once, after the
// whole run finishes.
const resultsDir = resolve(root, 'reports', '.a11y-results');
mkdirSync(resultsDir, { recursive: true });

// Every major public route (mirrors scripts/prerender.mjs's staticRoutes,
// plus one representative dynamic slug per family so Hindi/English book
// pages and a real blog post are both covered without scanning every
// single book/post individually).
const routes = [
  '/', '/books', '/about', '/blog', '/news', '/testimonials', '/start-here', '/write-together-hub', '/contact',
  '/media', '/readers', '/events', '/book-clubs', '/writing-resources',
  '/privacy-policy', '/terms', '/accessibility',
  '/books/the-shadow-code', '/books/offbeat-love', '/books/journey-of-grace',
  '/books/lalita-sahasranama', '/books/vishnu-sahasranama', '/books/anootha-pyar', '/books/nirdosh-gangster',
];

for (const route of routes) {
  test(`accessibility: ${route}`, async ({ page }) => {
    await page.goto(route);
    // Pages fetch their real content from Supabase client-side — without
    // this, axe can scan the page before the <h1>/body content has
    // rendered and wrongly report a missing heading.
    await page.waitForSelector('h1', { timeout: 10000 });
    const axe = await new AxeBuilder({ page }).analyze();

    const critical = axe.violations.filter((v) => v.impact === 'critical');
    const serious = axe.violations.filter((v) => v.impact === 'serious');
    const moderate = axe.violations.filter((v) => v.impact === 'moderate');
    const minor = axe.violations.filter((v) => v.impact === 'minor');

    const result = {
      route,
      critical: critical.length,
      serious: serious.length,
      moderate: moderate.length,
      minor: minor.length,
      violations: axe.violations.map((v) => ({
        id: v.id,
        impact: v.impact ?? 'unknown',
        help: v.help,
        nodes: v.nodes.map((n) => ({ target: n.target.join(' '), summary: n.failureSummary, html: n.html })),
      })),
    };
    const safeName = route === '/' ? 'home' : route.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '');
    writeFileSync(resolve(resultsDir, `${safeName}.json`), JSON.stringify(result, null, 2));

    // Only critical/serious violations fail the build — moderate/minor are
    // recorded in the report but don't block a deploy (see
    // docs/accessibility-test-results.md once generated).
    expect(critical.length, `critical a11y violations on ${route}: ${critical.map((v) => v.id).join(', ')}`).toBe(0);
    expect(serious.length, `serious a11y violations on ${route}: ${serious.map((v) => v.id).join(', ')}`).toBe(0);
  });
}

test.afterAll(() => {
  if (!existsSync(resultsDir)) return;
  const files = readdirSync(resultsDir).filter((f) => f.endsWith('.json'));
  if (files.length < routes.length) return; // wait until every worker's tests have written their file

  const results = files.map((f) => JSON.parse(readFileSync(resolve(resultsDir, f), 'utf-8')));

  const docsDir = resolve(root, 'docs');
  if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true });

  const totalCritical = results.reduce((n, r) => n + r.critical, 0);
  const totalSerious = results.reduce((n, r) => n + r.serious, 0);
  const totalModerate = results.reduce((n, r) => n + r.moderate, 0);
  const totalMinor = results.reduce((n, r) => n + r.minor, 0);

  const rows = results
    .sort((a, b) => a.route.localeCompare(b.route))
    .map((r) => `| \`${r.route}\` | ${r.critical} | ${r.serious} | ${r.moderate} | ${r.minor} |`)
    .join('\n');

  const detail = results
    .filter((r) => r.violations.length > 0)
    .map((r) => `### \`${r.route}\`\n\n${r.violations.map((v) =>
      `- **${v.id}** (${v.impact}): ${v.help}\n${v.nodes.map((n) => `  - \`${n.target}\`${n.summary ? ` — ${n.summary.split('\n')[0]}` : ''}`).join('\n')}`
    ).join('\n')}`)
    .join('\n\n');

  const md = `# Accessibility Test Results (axe-core)

Generated by \`e2e/accessibility.spec.ts\` (\`npm run test:e2e -- accessibility\`) against ${results.length} route(s).

CI fails the build on any **critical** or **serious** violation. Moderate/minor findings are recorded here but do not block a deploy.

## Summary

Total: ${totalCritical} critical, ${totalSerious} serious, ${totalModerate} moderate, ${totalMinor} minor.

| Route | Critical | Serious | Moderate | Minor |
|---|---|---|---|---|
${rows}

## Findings by page

${detail || '_No violations of any severity found._'}
`;

  writeFileSync(resolve(docsDir, 'accessibility-test-results.md'), md);
  rmSync(resultsDir, { recursive: true, force: true });
});
